"""Create WorkflowExample model

Revision ID: 25731da04b37
Revises: 92799b95f9ec
Create Date: 2025-08-05 20:20:59.117287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25731da04b37'
down_revision: Union[str, Sequence[str], None] = '92799b95f9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_output_examples', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_output_examples', 'description')
    # ### end Alembic commands ###
