"""add generation log field in workflow execution

Revision ID: 3f2ef6ade264
Revises: 673ef8620ced
Create Date: 2025-07-30 23:27:08.321903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2ef6ade264'
down_revision: Union[str, Sequence[str], None] = '673ef8620ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('generation_log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_executions', 'generation_log')
    # ### end Alembic commands ###
