"""add variables column to examples

Revision ID: 428cae443534
Revises: 5a5c29bd2911
Create Date: 2025-08-24 23:13:33.216358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428cae443534'
down_revision: Union[str, Sequence[str], None] = '5a5c29bd2911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_output_examples', sa.Column('variables', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_output_examples', 'variables')
    # ### end Alembic commands ###
