"""add is template field to output examples

Revision ID: 5a5c29bd2911
Revises: 25731da04b37
Create Date: 2025-08-24 22:50:05.431129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5c29bd2911'
down_revision: Union[str, Sequence[str], None] = '25731da04b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_output_examples', sa.Column('is_template', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_output_examples', 'is_template')
    # ### end Alembic commands ###
