"""Create WorkflowExample model

Revision ID: 92799b95f9ec
Revises: 3f2ef6ade264
Create Date: 2025-08-05 20:10:29.071722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92799b95f9ec'
down_revision: Union[str, Sequence[str], None] = '3f2ef6ade264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_output_examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('assets_workflow_id_fkey'), 'assets', type_='foreignkey')
    op.drop_column('assets', 'is_example')
    op.drop_column('assets', 'workflow_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('is_example', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('assets_workflow_id_fkey'), 'assets', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_table('workflow_output_examples')
    # ### end Alembic commands ###
