"""add internal path to asset

Revision ID: b36833b3e14e
Revises: b678493ddbbd
Create Date: 2025-08-25 00:07:30.335805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36833b3e14e'
down_revision: Union[str, Sequence[str], None] = 'b678493ddbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('internal_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'internal_path')
    # ### end Alembic commands ###
