"""add internal path

Revision ID: b678493ddbbd
Revises: 428cae443534
Create Date: 2025-08-24 23:23:13.068510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b678493ddbbd'
down_revision: Union[str, Sequence[str], None] = '428cae443534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_output_examples', sa.Column('internal_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_output_examples', 'internal_path')
    # ### end Alembic commands ###
